name: Build & Publish Container Image

on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        default: ${{ github.repository }}
      tag:
        required: false
        type: string
        default: ${{ github.sha }}
      registry:
        required: false
        type: string
        default: ghcr.io
      context:
        required: false
        type: string
        default: .
      file:
        required: false
        type: string
        default: ./Dockerfile
      publish:
        required: false
        type: boolean
        default: ${{ github.ref_name == 'main' }}

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Get commit timestamp
        id: commit_timestamp
        run: echo "timestamp=$(git show -s --format=%ct ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Log into Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Build OCI Container Images
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        env:
          SOURCE_DATE_EPOCH: ${{ steps.commit_timestamp.outputs.timestamp }}
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.publish }}
          tags: |
            ${{ inputs.registry }}/${{ inputs.name }}:${{ inputs.tag }}
            ${{ inputs.registry }}/${{ inputs.name }}:latest
          cache-from: type=gha,scope=${{ inputs.name }}
          cache-to: type=gha,mode=max,scope=${{ inputs.name }}
