name: Dockerfile Lint Check
description: Uses hadolint to check Dockerfiles for best practices and common issues.

on:
  workflow_call:
    inputs:
      file:
        required: false
        type: string
        default: "./Dockerfile"

jobs:
  lint:
    name: Hadolint Container Lint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Hadolint Lint Check
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: ${{ inputs.file }}
