name: Dockerfile Lint Check
description: Uses hadolint to check Dockerfiles for best practices and common issues.

on:
  workflow_call:
    inputs:
      file:
        required: false
        type: string
        default: "./Dockerfile"

jobs:
  lint:
    name: Hadolint Container Lint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Hadolint Lint Check
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ${{ inputs.file }}
