name: ESlint Lint Check

on:
  workflow_call:
    inputs:
      eslint-version:
        required: false
        type: string
        default: "latest"
      check-path:
        required: false
        type: string
        default: "."
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"

jobs:
  lint:
    name: ESlint Lint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: latest
          cache: ${{ inputs.cache-dependency-manager }}

      - name: Install Dependencies
        run: npm ci

      - name: Run ESlint
        run: npx eslint@${{ inputs.eslint-version }} ${{ inputs.check-path }}
