name: Markdown Lint Check

on:
  workflow_call:
    inputs:
      markdownlint-version:
        required: false
        type: string
        default: "latest"

jobs:
  format:
    name: Markdown Lint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: latest

      - name: Lint Check
        run: npx markdownlint-cli2@${{ inputs.markdownlint-version }}
