name: npm Test

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "latest"
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"
      registry-url:
        required: false
        type: string
        default: "https://npm.pkg.github.com"
      package-scope:
        required: false
        type: string
        default: "@bymbly"

jobs:
  test:
    name: npm Test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache-dependency-manager }}
          registry-url: ${{ inputs.registry-url }}
          scope: ${{ inputs.package-scope }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
