name: npm Semantic Release

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: ""
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"
      registry-url:
        required: false
        type: string
        default: "https://npm.pkg.github.com"
      package-scope:
        required: false
        type: string
        default: "@bymbly"
    secrets:
      NPM_TOKEN:
        required: false
        description: npm authentication token for publishing packages to npm.org

jobs:
  semantic-release:
    name: npm Semantic Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: ./.github/actions/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache-dependency-manager }}
          registry-url: ${{ inputs.registry-url }}
          scope: ${{ inputs.package-scope }}

      - name: Install Dependencies
        run: npm ci

      - name: Verify dependencies
        run: npm audit signatures

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN || secrets.GITHUB_TOKEN }}
