name: Publish Node.js Package

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: ""
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"
      registry-url:
        required: false
        type: string
        default: "https://npm.pkg.github.com"
      package-scope:
        required: false
        type: string
        default: "@bymbly"
      package-tag:
        required: false
        type: string
        default: "latest"
    secrets:
      NPM_TOKEN:
        required: false
        description: npm authentication token for publishing packages to npm.org

jobs:
  publish:
    name: Publish Node.js Package
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: ./.github/actions/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache-dependency-manager }}
          registry-url: ${{ inputs.registry-url }}
          scope: ${{ inputs.package-scope }}

      - run: npm ci
      - run: npm audit signatures
      - run: npm publish --tag ${{ inputs.package-tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN || secrets.GITHUB_TOKEN }}
