name: Publish Node.js Package

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "latest"
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"
      registry-url:
        required: false
        type: string
        default: "https://npm.pkg.github.com"
      package-scope:
        required: false
        type: string
        default: "@bymbly"
      package-tag:
        required: false
        type: string
        default: "latest"

jobs:
  publish:
    name: Publish Node.js Package
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache-dependency-manager }}
          registry-url: ${{ inputs.registry-url }}
          scope: ${{ inputs.package-scope }}

      - run: npm ci
      - run: npm publish --tag ${{ inputs.package-tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
