name: npm Test

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: ""
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"
      registry-url:
        required: false
        type: string
        default: "https://npm.pkg.github.com"
      package-scope:
        required: false
        type: string
        default: "@bymbly"

jobs:
  test:
    name: npm Test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: bymbly/gha-workflows/.github/actions/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache-dependency-manager }}
          registry-url: ${{ inputs.registry-url }}
          scope: ${{ inputs.package-scope }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
