name: Prettier Format Check

on:
  workflow_call:
    inputs:
      prettier-version:
        required: false
        type: string
        default: "latest"
      check-path:
        required: false
        type: string
        default: "."
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"

jobs:
  format:
    name: Prettier Format Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: latest
          cache: ${{ inputs.cache-dependency-manager }}

      - name: Check Formatting
        run: npx prettier@${{ inputs.prettier-version }} --check ${{ inputs.check-path }}
