name: Prettier Format Check

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: ""
      prettier-version:
        required: false
        type: string
        default: ""
      check-path:
        required: false
        type: string
        default: "."
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"

jobs:
  format:
    name: Prettier Format Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: bymbly/gha-workflows/.github/actions/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache-dependency-manager }}

      - name: Install Dependencies
        run: npm ci

      - name: Check Formatting
        run: npx --yes prettier${{ inputs.prettier-version && format('@{0}', inputs.prettier-version) || '' }} --check ${{ inputs.check-path }}
