name: Prettier Format Check

on:
  workflow_call:
    inputs:
      prettier-version:
        required: false
        type: string
        default: "latest"
      check-path:
        required: false
        type: string
        default: "."

jobs:
  format:
    name: Prettier Format Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: latest

      - name: Check Formatting
        run: npx prettier@${{ inputs.prettier-version }} --check ${{ inputs.check-path }}
