name: Redocly Bundle Lint Check

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: ""
      redocly-version:
        required: false
        type: string
        default: "latest"
      openapi-file:
        required: false
        type: string
        default: "./openapi/openapi.yaml"
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"

jobs:
  bundle-lint:
    name: Redocly Bundle Lint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: bymbly/gha-workflows/.github/actions/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache-dependency-manager }}

      - name: Install Dependencies
        run: npm ci

      - name: Bundle APIs
        run: npx @redocly/cli@${{ inputs.redocly-version }} bundle ${{ inputs.openapi-file }} --output bundled.yaml

      - name: Lint Check
        run: npx @redocly/cli@${{ inputs.redocly-version }} lint bundled.yaml
