name: Redocly Bundle Lint Check

on:
  workflow_call:
    inputs:
      redocly-version:
        required: false
        type: string
        default: "latest"
      openapi-file:
        required: false
        type: string
        default: "./openapi/openapi.yaml"
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"

jobs:
  bundle-lint:
    name: Redocly Bundle Lint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: latest
          cache: ${{ inputs.cache-dependency-manager }}

      - name: Bundle APIs
        run: npx @redocly/cli@${{ inputs.redocly-version }} bundle ${{ inputs.openapi-file }} --output bundled.yaml

      - name: Lint Check
        run: npx @redocly/cli@${{ inputs.redocly-version }} lint bundled.yaml
