name: Redocly Lint Check

on:
  workflow_call:
    inputs:
      redocly-version:
        required: false
        type: string
        default: "latest"
      apis:
        # by default, lint all apis specified in redocly.yaml
        required: false
        type: string
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"

jobs:
  lint:
    name: Redocly Lint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: latest
          cache: ${{ inputs.cache-dependency-manager }}

      - name: Lint Check
        run: npx @redocly/cli@${{ inputs.redocly-version }} lint ${{ inputs.apis }}
