name: Spectral Lint Check

on:
  workflow_call:
    inputs:
      spectral-version:
        required: false
        type: string
        default: "latest"
      file-glob:
        required: false
        type: string
        default: "./{openapi, asyncapi, arazzo}/*{json,yml,yaml}"

jobs:
  lint:
    name: Spectral Lint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: latest

      - name: Cache npm packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache-${{ runner.os }}

      - name: Lint Check
        run: npx @stoplight/spectral-cli@${{ inputs.spectral-version }} lint --fail-severity warn ${{ inputs.file-glob }}
