name: Spectral Lint Check

on:
  workflow_call:
    inputs:
      spectral-version:
        required: false
        type: string
        default: "latest"
      file-glob:
        required: false
        type: string
        default: "./{openapi, asyncapi, arazzo}/*{json,yml,yaml}"
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"

jobs:
  lint:
    name: Spectral Lint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: latest
          cache: ${{ inputs.cache-dependency-manager }}

      - name: Lint Check
        run: npx @stoplight/spectral-cli@${{ inputs.spectral-version }} lint --fail-severity warn ${{ inputs.file-glob }}
