name: Spectral Lint Check

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: ""
      spectral-version:
        required: false
        type: string
        default: "latest"
      file-glob:
        required: false
        type: string
        default: "./{openapi, asyncapi, arazzo}/*{json,yml,yaml}"
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"

jobs:
  lint:
    name: Spectral Lint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: bymbly/gha-workflows/.github/actions/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache-dependency-manager }}

      - name: Lint Check
        run: npx @stoplight/spectral-cli@${{ inputs.spectral-version }} lint --fail-severity warn ${{ inputs.file-glob }}
